package org.pathwayeditor.businessobjects.hibernate.pojos;


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import org.pathwayeditor.businessobjects.repository.IFolder;

/**
 * Folder generated by hbm2java
 */
public abstract class HibFolder implements Serializable {
	private static final long serialVersionUID = 8668639813872187460L;
	private Long id;
	private Set<HibMapDiagram> hibMapDiagrams = new HashSet<HibMapDiagram>(0);
	private Set<HibSubFolder> subFolders = new HashSet<HibSubFolder>(0);
	private HibRepository repository;
	private int iNode= makeIntUUID();

	public HibFolder() {
	}

	/**
	 * @return a int representation of the first 8 digits in a real UUID
	 */
	private int makeIntUUID() { //FIXME - this IS NOT GUARANTEED UNIQUE!!!!!!!!!!!!!
		Long tempL= UUID.randomUUID().getMostSignificantBits();
		return tempL.intValue();
	}

	public HibFolder(HibFolder other) {
		for (HibMapDiagram diagram : other.getMapDiagrams()) {
			this.hibMapDiagrams.add(new HibMapDiagram(this, diagram));
		}
		for (HibSubFolder subFolder : other.getSubFolders()) {
			this.subFolders.add(new HibSubFolder(this, subFolder));
		}
	}

	public Long getId() {
		return this.id;
	}

	void setId(Long id) {
		this.id = id;
	}

	public void setRepository(HibRepository repository) {
		this.repository = repository;
	}

	public HibRepository getRepository() {
		return repository;
	}

	public Set<HibMapDiagram> getMapDiagrams() {
		return this.hibMapDiagrams;
	}

	void setMapDiagrams(Set<HibMapDiagram> hibMapDiagrams) {
		this.hibMapDiagrams = hibMapDiagrams;
	}

	public Set<HibSubFolder> getSubFolders() {
		return this.subFolders;
	}

	void setSubFolders(Set<HibSubFolder> subFolders) {
		this.subFolders = subFolders;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	void addSubFolder(HibSubFolder newSubFolder) {
		if (newSubFolder == null)
			throw new IllegalArgumentException("newSubFolder cannot be null");

		HibFolder oldParentFolder = newSubFolder.getParentFolder();
		if (oldParentFolder != null) {
			oldParentFolder.subFolders.remove(newSubFolder);
		}
		this.subFolders.add(newSubFolder);
		newSubFolder.setParentFolder(this);
	}

	void removeSubFolder(HibSubFolder subFolder) {
		if (subFolder == null)
			throw new IllegalArgumentException("subFolder cannot be null");
		if (subFolder.getParentFolder() != this)
			throw new IllegalArgumentException(
					"subFolder must be a child of this folder");

		this.subFolders.remove(subFolder);
		subFolder.setParentFolder(null);
	}
	
	void addMapDiagram(HibMapDiagram newMapDiagram) {
		if (newMapDiagram == null)
			throw new IllegalArgumentException("newMapDiagram cannot be null");

		HibFolder oldParentFolder = newMapDiagram.getFolder();
		if (oldParentFolder != null) {
			oldParentFolder.getMapDiagrams().remove(newMapDiagram);
		}
		this.hibMapDiagrams.add(newMapDiagram);
		newMapDiagram.setFolder(this);
	}

	void removeMapDiagram(HibMapDiagram mapDiagram) {
		if (mapDiagram == null)
			throw new IllegalArgumentException("mapDiagram cannot be null");
		if (mapDiagram.getFolder() != this)
			throw new IllegalArgumentException(
					"mapDiagram must belong to this folder");

		this.hibMapDiagrams.remove(mapDiagram);
		mapDiagram.setFolder(null);
	}
	
	public abstract IFolder getBusinessObject();
	
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj){
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if(!(obj instanceof HibFolder)){
			return false;
		}
		final HibFolder other = (HibFolder) obj;
		if(id!=null&&other.getId()!=null&&id.equals(other.getId()))     //FIXME - replace with INODE code
			return true;
		return false;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return 31 + (id==null?0:id.hashCode());   //FIXME - replace with INODE code
	}

	protected int getINode() {
		return this.iNode;
	}

	protected void setINode(int node) {
		this.iNode = node;
	}

}
