package org.pathwayeditor.businessobjects.hibernate.pojos;

import java.io.Serializable;

import org.pathwayeditor.businessobjects.drawingprimitives.ILinkEnd;
import org.pathwayeditor.businessobjects.drawingprimitives.ILinkEndDecoration;
import org.pathwayeditor.businessobjects.typedefn.ILinkEndDefinition;



/**
 * LinkEndDecorator generated by hbm2java
 */
public class HibLinkEndDecorator  implements ILinkEndDecoration ,Serializable {

	
     private Long id;
     private HibLinkTerminus hibLinkTerminus;
     private short decoratorType;
     private int width;
     private int height;
     private int gap ;

    public HibLinkEndDecorator() {
    }

    public HibLinkEndDecorator(HibLinkTerminus hibLinkTerminus, short decoratorType, int width, int height , int gap) {
       this.hibLinkTerminus = hibLinkTerminus;
       this.decoratorType = decoratorType;
       this.width = width;
       this.height = height;
       this.gap = gap ;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public HibLinkTerminus getLinkTerminus() {
        return this.hibLinkTerminus;
    }
    
    public void setLinkTerminus(HibLinkTerminus hibLinkTerminus) {
        this.hibLinkTerminus = hibLinkTerminus;
    }
    public short getDecoratorType() {
        return this.decoratorType;
    }
    
    public void setDecoratorType(short decoratorType) {
        this.decoratorType = decoratorType;
    }
    public int getWidth() {
        return this.width;
    }
    
    public void setWidth(int width) {
        this.width = width;
    }
    public int getHeight() {
        return this.height;
    }
    
    public void setHeight(int height) {
        this.height = height;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HibLinkEndDecorator) ) return false;
		 HibLinkEndDecorator castOther = ( HibLinkEndDecorator ) other; 
         
		 return ( (this.getLinkTerminus()==castOther.getLinkTerminus()) || ( this.getLinkTerminus()!=null && castOther.getLinkTerminus()!=null && this.getLinkTerminus().equals(castOther.getLinkTerminus()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLinkTerminus() == null ? 0 : this.getLinkTerminus().hashCode() );
         
         return result;
   }   

  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = 6500668023572752002L;

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkEndDecoration#getGap()
	 */
	public int getGap() {
		return this.gap;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkEndDecoration#getLinkEnd()
	 */
	public ILinkEnd getLinkEnd() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkEndDecoration#getLinkEndDefinition()
	 */
	public ILinkEndDefinition getLinkEndDefinition() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkEndDecoration#setGap(int)
	 */
	public void setGap(int newGap) {
		this.gap = newGap ;		
	}
    	
  // end of extra code specified in the hbm.xml files

}


