package org.pathwayeditor.businessobjects.hibernate.pojos;

// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute;
import org.pathwayeditor.businessobjects.drawingprimitives.attributes.ConnectionRouter;
import org.pathwayeditor.businessobjects.drawingprimitives.attributes.IBendPoint;
import org.pathwayeditor.businessobjects.drawingprimitives.attributes.LineStyle;
import org.pathwayeditor.businessobjects.drawingprimitives.attributes.LinkTermType;
import org.pathwayeditor.businessobjects.drawingprimitives.attributes.Location;
import org.pathwayeditor.businessobjects.drawingprimitives.attributes.RGB;
import org.pathwayeditor.businessobjects.drawingprimitives.attributes.Size;
import org.pathwayeditor.businessobjects.drawingprimitives.listeners.IPropertyChangeListener;
import org.pathwayeditor.businessobjects.drawingprimitives.listeners.ListenablePropertyChangeItem;
import org.pathwayeditor.businessobjects.drawingprimitives.listeners.PropertyChange;
import org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotationProperty;
import org.pathwayeditor.businessobjects.drawingprimitives.properties.IPropertyBuilder;
import org.pathwayeditor.businessobjects.drawingprimitives.properties.IPropertyDefinition;
import org.pathwayeditor.businessobjects.hibernate.helpers.InconsistentNotationDefinitionException;
import org.pathwayeditor.businessobjects.hibernate.helpers.PropertyBuilder;
import org.pathwayeditor.businessobjects.hibernate.pojos.graph.IterationCaster;
import org.pathwayeditor.businessobjects.typedefn.ILinkAttributeDefaults;
import org.pathwayeditor.businessobjects.typedefn.ILinkObjectType;

import uk.ed.inf.graph.util.IndexCounter;

/**
 * Link generated by hbm2java
 */
public class HibLinkAttribute implements ILinkAttribute , Serializable {
	private static final long serialVersionUID = 8124494867402957446L;

	private RGB DEFAULT_LINE_COLOUR = new RGB(255, 255, 255);
	private Long id;
	private HibCanvas hibCanvas;
	private int creationSerial;
	private HibObjectType hibObjectType;
	private ILinkObjectType objectType;
	private String name;
	private String description;
	private String detailedDescription;
	private String url;
	private RGB lineColour = DEFAULT_LINE_COLOUR;
	private LineStyle lineStyle;
	private int lineWidth;
	private ConnectionRouter routerType;
	private List<HibBendPoint> hibBendPoints = new ArrayList<HibBendPoint>(0);
//	private HibLinkTerminus sourceTerminus;
//	private HibLinkTerminus targetTerminus;
//	private HibLinkEdge edge ;
	private Map<String, HibProperty> hibLinkProperties = new HashMap<String, HibProperty>(0);
	private IPropertyBuilder propertyBuilder;
	private List<HibLinkTerminus> linkTermini = new ArrayList<HibLinkTerminus>(0);
	private IndexCounter bendPointCounter = new IndexCounter();
	private final ListenablePropertyChangeItem listenablePropertyChangeItem = new ListenablePropertyChangeItem();

	/**
	 * Default constructor to be used only by hibernate.
	 * @deprecated use any of the other constructors to construct this class in application code.
	 */
	HibLinkAttribute() {
	}

	/**
	 * Constructs new instance of this class.
	 * @param hibCanvas
	 * @param linkIndex
	 * @param objectType
	 * @param hibObjectType
	 */
	public HibLinkAttribute(HibCanvas hibCanvas, int linkIndex, ILinkObjectType objectType, HibObjectType hibObjectType) {
		this.hibCanvas = hibCanvas;
		this.propertyBuilder = new PropertyBuilder(hibCanvas);
		this.creationSerial = linkIndex;
		this.objectType = objectType;
		this.hibObjectType = hibObjectType;
//		this.sourceTerminus = new HibLinkTerminus(this, LinkTermType.SOURCE, objectType.getSourceTerminusDefinition());
//		this.targetTerminus = new HibLinkTerminus(this, LinkTermType.TARGET, objectType.getTargetTerminusDefinition());
		this.linkTermini.add(new HibLinkTerminus(this, LinkTermType.TARGET, objectType.getTargetTerminusDefinition()));
		this.linkTermini.add(new HibLinkTerminus(this, LinkTermType.SOURCE, objectType.getSourceTerminusDefinition()));
		addDefaults(objectType.getDefaultLinkAttributes());
		this.getCanvas().getLinkAttributes().add(this) ;
	}

	/**
	 * Constructs new instance that is a copy of another one.
	 * @param hibCanvas
	 * @param linkIndex
	 * @param otherAttribute
s	 */
	public HibLinkAttribute(HibCanvas hibCanvas, int linkIndex, HibLinkAttribute otherAttribute) {
		this.hibCanvas = hibCanvas;
		this.propertyBuilder = new PropertyBuilder(hibCanvas);
		this.creationSerial = linkIndex;
		this.objectType = otherAttribute.objectType;
		this.hibObjectType = otherAttribute.hibObjectType;
//		this.sourceTerminus = new HibLinkTerminus(this, otherAttribute.getSourceTerminus());
//		this.targetTerminus = new HibLinkTerminus(this, otherAttribute.getTargetTerminus());
		this.lineColour = otherAttribute.getLineColor();
		this.lineStyle = otherAttribute.getLineStyle();
		this.lineWidth = otherAttribute.getLineWidth();
		this.name = otherAttribute.getName();
		this.description = otherAttribute.getDescription();
		this.detailedDescription = otherAttribute.getDetailedDescription();
		this.url = otherAttribute.getUrl();
		this.routerType = otherAttribute.getRouter();
		for(HibProperty prop : otherAttribute.hibLinkProperties.values()){
			HibProperty copiedProp = (HibProperty)prop.getDefinition().copyProperty(this.propertyBuilder, prop);
			this.hibLinkProperties.put(copiedProp.getDefinition().getName(), copiedProp);
		}
//		for(HibLinkTerminus linkTerm : otherAttribute.getLinkTermini()){
//			HibLinkTerminus copiedTerminus = new HibLinkTerminus(this, linkTerm);
//			this.linkTermini.add(copiedTerminus);
//		}
		this.getCanvas().getLinkAttributes().add(this) ;
	}

	/**
	 * @param linkAttributeDefaults
	 */
	private void addDefaults(ILinkAttributeDefaults linkAttributeDefaults) {
		this.lineColour = linkAttributeDefaults.getLineColour();
		this.lineStyle = linkAttributeDefaults.getLineStyle();
		this.lineWidth = linkAttributeDefaults.getLineWidth();
		this.name = linkAttributeDefaults.getName();
		this.description = linkAttributeDefaults.getDescription();
		this.detailedDescription = linkAttributeDefaults.getDetailedDescription();
		this.url = linkAttributeDefaults.getUrl();
		this.routerType = linkAttributeDefaults.getRouter();
		Iterator<IPropertyDefinition> propIter = linkAttributeDefaults.propertyDefinitionIterator();
		while(propIter.hasNext()){
			IPropertyDefinition propDefn = propIter.next();
			this.hibLinkProperties.put(propDefn.getName(), (HibProperty)propDefn.createProperty(propertyBuilder));
		}
	}

	public Long getId() {
		return this.id;
	}
	
//	void setLinkEdge(HibLinkEdge edge) {
//		this.edge = edge;
//	}
//	
//	public void changeLinkEdge(HibLinkEdge newEdge){
//		if(this.edge != null){
//			this.edge.setAttribute(null);
//		}
//		if(newEdge != null){
//			newEdge.setAttribute(this);
//		}
//		this.edge = newEdge;
//	}

	@SuppressWarnings("unused")
	private void setId(Long id) {
		this.id = id;
	}

	public HibCanvas getCanvas() {
		return this.hibCanvas;
	}

	public void setCanvas(HibCanvas hibCanvas) {
		if(hibCanvas != null){
			this.propertyBuilder = new PropertyBuilder(hibCanvas);
		}
		else{
			this.propertyBuilder = null;
		}
		this.hibCanvas = hibCanvas;
	}

	public void changeHibCanvas(HibCanvas canvas){
		if(this.hibCanvas != null){
			this.hibCanvas.getLinkAttributes().remove(this);
		}
		if(canvas != null){
			canvas.getLinkAttributes().add(this);
		}
		this.setCanvas(canvas);
	}
	
	public int getCreationSerial() {
		return this.creationSerial;
	}

	public void setCreationSerial(int link_index) {
		this.creationSerial = link_index;
	}

	public ILinkObjectType getObjectType() {
		return this.objectType;
	}
	
	public HibObjectType getHibObjectType () {
		return this.hibObjectType ;
	}
	
	void setHibObjectType (HibObjectType hibObjectType) {
		this.hibObjectType = hibObjectType ;
	}

	public void injectLinkObjectType(ILinkObjectType objectType) throws InconsistentNotationDefinitionException {
		this.objectType = objectType;
		injectPropertyDefinitions();
		this.getSourceTerminus().injectLinkTerminusDefaults(objectType.getSourceTerminusDefinition());
		this.getTargetTerminus().injectLinkTerminusDefaults(objectType.getTargetTerminusDefinition());
	}

	private void injectPropertyDefinitions() throws InconsistentNotationDefinitionException {
		Iterator<IPropertyDefinition> it = this.objectType.getDefaultLinkAttributes().propertyDefinitionIterator();
		int propCntr = 0;
		while (it.hasNext()) {
			IPropertyDefinition definition = it.next();
			HibProperty property = this.hibLinkProperties.get(definition.getName());
			if(property==null) {
					throw new InconsistentNotationDefinitionException("The object type has property definitions which have no matching property in this Shape Attribute");
			}
			property.setPropertyDefinition(definition);
			propCntr++;
		}
		if(propCntr != this.hibLinkProperties.size()) {
			throw new InconsistentNotationDefinitionException("Object inconsistent with object type. Cannot find definitions for some properties");
		}
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		String oldValue = this.name;
		this.name = name;
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.NAME, oldValue, this.name);
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		String oldValue = this.name;
		this.description = description;
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.DESCRIPTION, oldValue, this.description);
	}

	public String getDetailedDescription() {
		return this.detailedDescription;
	}

	public void setDetailedDescription(String detailedDescription) {
		String oldValue = this.detailedDescription;
		this.detailedDescription = detailedDescription;
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.DETAILED_DESCRIPTION, oldValue, this.detailedDescription);
}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		String oldValue = this.url;
		this.url = url;
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.URL, oldValue, this.url);
	}

	public Map<String, HibProperty> getLinkProperties() {
		return this.hibLinkProperties;
	}

	public void setHibLinkProperties(Map<String, HibProperty> hibProperties) {
		this.hibLinkProperties = hibProperties;
	}

	public int getLineRed() {
		return this.lineColour.getRed();
	}

	public void setLineRed(int lineRed) {
		this.lineColour = this.lineColour.newRed(lineRed);
	}

	public Map<String, ? extends IAnnotationProperty> getHibLinkProperties() {
		return this.hibLinkProperties;
	}

	public int getLineGreen() {
		return this.lineColour.getGreen();
	}

	public void setLineGreen(int lineGreen) {
		this.lineColour = this.lineColour.newGreen(lineGreen);
	}

	public int getLineBlue() {
		return this.lineColour.getBlue();
	}

	public void setLineBlue(int lineBlue) {
		this.lineColour = this.lineColour.newBlue(lineBlue);
	}

	public LineStyle getLineStyle() {
		return this.lineStyle;
	}

	public void setLineStyle(LineStyle lineStyle) {
		if ( lineStyle == null )
			throw new IllegalArgumentException ( "Line style cannot be null." ) ;
		
		LineStyle oldValue = this.lineStyle;
		this.lineStyle = lineStyle;
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.LINE_STYLE, oldValue, this.lineStyle);
	}

	public int getLineWidth() {
		return this.lineWidth;
	}

	public void setLineWidth(int lineWidth) {
		int oldValue = this.lineWidth;
		this.lineWidth = lineWidth;
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.LINE_WIDTH, oldValue, this.lineWidth);
	}

	public ConnectionRouter getRouterType() {
		return this.routerType;
	}

	public void setRouterType(ConnectionRouter routerType) {
		ConnectionRouter oldValue = this.routerType;
		this.routerType = routerType;
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.ROUTER_TYPE, oldValue, this.routerType);
	}

	public List<HibBendPoint> getBendPoints() {
		return this.hibBendPoints;
	}

	void setBendPoints(List<HibBendPoint> hibBendPoints) {
		this.hibBendPoints = hibBendPoints;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((this.hibCanvas == null) ? 0 : this.hibCanvas.hashCode());
		result = prime * result + this.creationSerial;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final HibLinkAttribute other = (HibLinkAttribute) obj;
		if (this.hibCanvas == null) {
			if (other.hibCanvas != null)
				return false;
		} else if (!this.hibCanvas.equals(other.hibCanvas))
			return false;
		if (this.creationSerial != other.creationSerial)
			return false;
		return true;
	}

//	void addLinkProperty ( String name , HibProperty toAdd ) 
//	{
//		if (toAdd == null)
//			throw new IllegalArgumentException("property cannot be null");
//		this.hibLinkProperties.put(name ,toAdd);
//	}
//	
//	void removeLinkProperty(String toRemove) {
//		if (toRemove == null)
//			throw new IllegalArgumentException("id cannot be null");
//		HibProperty propertyToRemove = hibLinkProperties.get(toRemove) ;
//		if  (propertyToRemove == null)
//			throw new IllegalStateException("property cannot be null");
//		
//		this.hibLinkProperties.remove(toRemove) ;
//	}
	
	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILink#bendPointIterator()
	 */
	public Iterator<IBendPoint> bendPointIterator() {
		List<IBendPoint> bendPoints = new ArrayList<IBendPoint> ( this.hibBendPoints) ;
		return bendPoints.iterator();
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILink#containsBendPoint(org.pathwayeditor.businessobjects.drawingprimitives.attributes.IBendPoint)
	 */
	public boolean containsBendPoint(IBendPoint bendPoint) {
		boolean retVal = false;
		if ( bendPoint != null && bendPoint.getOwningLink() == this){
			retVal = this.hibBendPoints.contains((HibBendPoint) bendPoint );
		}
		return retVal;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILink#getRouter()
	 */
	public ConnectionRouter getRouter() {
		return this.routerType ;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILink#numBendPoints()
	 */
	public int numBendPoints() {
		return hibBendPoints.size();
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILink#removeBendPoint(org.pathwayeditor.businessobjects.drawingprimitives.attributes.IBendPoint)
	 */
	public void removeBendPoint(IBendPoint bendPoint) {
		if ( !containsBendPoint(bendPoint) ) new IllegalArgumentException ("no bendpoint") ;

		HibBendPoint hibBendPoint = (HibBendPoint)bendPoint; 
		this.hibBendPoints.remove(hibBendPoint);
		// break link to this attribute so it will be deleted.
		hibBendPoint.setOwningLink(null);
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.BEND_POINT_REMOVED, null, null);
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILink#setRouter(org.pathwayeditor.businessobjects.drawingprimitives.attributes.ConnectionRouter)
	 */
	public void setRouter(ConnectionRouter router) {
		if ( router == null)
			throw new IllegalArgumentException("Router cannot be null.");
		this.routerType = router ;
		
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotatedObject#getProperty(org.pathwayeditor.businessobjects.typedefn.IPropertyDefinition)
	 */
	public IAnnotationProperty getProperty(IPropertyDefinition propDefn) {
		return this.hibLinkProperties.get(propDefn.getName());
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotatedObject#getProperty(java.lang.String)
	 */
	public IAnnotationProperty getProperty(String propName) {
		return this.hibLinkProperties.get(propName);
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotatedObject#propertyIterator()
	 */
	public Iterator<IAnnotationProperty> propertyIterator() {
		return new IterationCaster<IAnnotationProperty, HibProperty>(this.hibLinkProperties.values().iterator());
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#getLineColor()
	 */
	public RGB getLineColor() {
		return this.lineColour;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#setLineColor(org.pathwayeditor.businessobjects.drawingprimitives.attributes.RGB)
	 */
	public void setLineColor(RGB newColor) {
		if ( newColor == null)
			throw new IllegalArgumentException () ;

		RGB oldValue = this.lineColour;
		this.lineColour = newColor;
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.LINE_COLOUR, oldValue, this.lineStyle);
	}

//	/* (non-Javadoc)
//	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#getLinkEdge()
//	 */
//	public ILinkEdge getLinkEdge() {
//		return this.edge;
//	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ICanvasAttribute#hasProperty(org.pathwayeditor.businessobjects.drawingprimitives.properties.IPropertyDefinition)
	 */
	public boolean hasProperty(IPropertyDefinition property) {
		boolean retVal = false;
		if(property != null){
			retVal = this.hibLinkProperties.containsKey(property.getName());
		}
		return retVal;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#getLinkSourceDecoration()
	 */
//	public HibLinkTerminus getSourceTerminus() {
//		return this.sourceTerminus;
//	}
//
//	/* (non-Javadoc)
//	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#getLinkTargetDecoration()
//	 */
//	public HibLinkTerminus getTargetTerminus() {
//		return this.targetTerminus;
//	}
//
//	public void setSourceTerminus(HibLinkTerminus sourceTerminus) {
//		this.sourceTerminus = sourceTerminus;
//	}
//
//	public void setTargetTerminus(HibLinkTerminus targetTerminus) {
//		this.targetTerminus = targetTerminus;
//	}
	
	public List<HibLinkTerminus> getLinkTermini() {
		return this.linkTermini;
	}

	public void setLinkTermini(List<HibLinkTerminus> linkTermini) {
		this.linkTermini = linkTermini;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#getSourceTerminus()
	 */
	public HibLinkTerminus getSourceTerminus() {
		return this.linkTermini.get(LinkTermType.SOURCE.toInt());
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#getTargetTerminus()
	 */
	public HibLinkTerminus getTargetTerminus() {
		return this.linkTermini.get(LinkTermType.TARGET.toInt());
	}

	
	void setLastBendPointSerial(int lastSerial) {
		this.bendPointCounter = new IndexCounter(lastSerial);
	}
	

	int getLastBendPointSerial() {
		return this.bendPointCounter.getLastIndex();
	}
	

	@Override
	public String toString(){
		StringBuilder builder = new StringBuilder(this.getClass().getSimpleName());
		builder.append("(canvas=");
		builder.append(this.getCanvas());
		builder.append(", serial=");
		builder.append(this.getCreationSerial());
		builder.append(")");
		return builder.toString();
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.listeners.IPropertyChangeListenee#addChangeListener(org.pathwayeditor.businessobjects.drawingprimitives.listeners.IPropertyChangeListener)
	 */
	public void addChangeListener(IPropertyChangeListener listener) {
		this.listenablePropertyChangeItem.addChangeListener(listener);
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.listeners.IPropertyChangeListenee#listenerIterator()
	 */
	public Iterator<IPropertyChangeListener> listenerIterator() {
		return this.listenablePropertyChangeItem.listenerIterator();
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.listeners.IPropertyChangeListenee#removeChangeListener(org.pathwayeditor.businessobjects.drawingprimitives.listeners.IPropertyChangeListener)
	 */
	public void removeChangeListener(IPropertyChangeListener listener) {
		this.listenablePropertyChangeItem.removeChangeListener(listener);
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#addbendPoint(org.pathwayeditor.businessobjects.drawingprimitives.attributes.IBendPoint, int)
	 */
	public void changeBendPointPosition(IBendPoint bendPoint, int indexPos) {
		if(!this.containsBendPoint(bendPoint)) throw new IllegalArgumentException("bendPoint must be contained by this attribute");

		if(indexPos >= this.hibBendPoints.size() || indexPos < 0){
			throw new IndexOutOfBoundsException("list size= " + this.hibBendPoints.size() + ", no bendpoint at position: " + indexPos);
		}
		else{
			int oldIdx = this.hibBendPoints.indexOf(bendPoint);
			if(indexPos < this.hibBendPoints.size()-1) {
				this.hibBendPoints.remove(oldIdx);
				// insert at new position
				this.hibBendPoints.add(indexPos, (HibBendPoint)bendPoint);
			}
			else {
				this.hibBendPoints.remove(oldIdx);
				// we want to add it to the end of the list so we append it bp to the list.
				this.hibBendPoints.add((HibBendPoint)bendPoint);
			}
			this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.BEND_POINT_REINDEXED, oldIdx, indexPos);
		}
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#containsBendPoint(int)
	 */
	public boolean containsBendPoint(int index) {
		boolean retVal = index >= 0 && index < this.hibBendPoints.size();
		if(retVal){
			retVal = this.hibBendPoints.get(index) != null; 
		}
		return retVal;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#getBendPoint(int)
	 */
	public IBendPoint getBendPoint(int index) {
		if(!containsBendPoint(index)) throw new IllegalArgumentException("not bendpoint at this index position");
		
		return this.hibBendPoints.get(index);
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#removeBendPoint(int)
	 */
	public void removeBendPoint(int index) {
		if(!containsBendPoint(index)) throw new IllegalArgumentException("not bendpoint at this index position");

		HibBendPoint hibBendPoint = this.hibBendPoints.get(index);
		this.hibBendPoints.remove(index);
		hibBendPoint.setOwningLink(null);
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.BEND_POINT_REMOVED, null, null);
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkAttribute#createNewBendPoint(org.pathwayeditor.businessobjects.drawingprimitives.attributes.Location, org.pathwayeditor.businessobjects.drawingprimitives.attributes.Location, org.pathwayeditor.businessobjects.drawingprimitives.attributes.Location)
	 */
	public IBendPoint createNewBendPoint(Location location, Size firstRelativeDim, Size secondRelativeDim) {
		HibBendPoint retVal = new HibBendPoint(this, this.bendPointCounter.nextIndex(), location, firstRelativeDim, secondRelativeDim);
		this.hibBendPoints.add(retVal);
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.BEND_POINT_ADDED, null, retVal);
		return retVal;
	}

	public IBendPoint createNewBendPoint(int position, Location location, Size firstRelativeDim, Size secondRelativeDim) {
		HibBendPoint retVal = new HibBendPoint(this, this.bendPointCounter.nextIndex(), location, firstRelativeDim, secondRelativeDim);
		if(position < 0 || position > this.hibBendPoints.size()) {
			throw new IndexOutOfBoundsException("list size= " + this.hibBendPoints.size() + ", no bendpoint can be added at position: " + position);
		}
		else if(position < this.hibBendPoints.size()) {
			this.hibBendPoints.add(position, retVal);
		}
		else {
			this.hibBendPoints.add(retVal);
		}
		this.listenablePropertyChangeItem.notifyProperyChange(PropertyChange.BEND_POINT_ADDED, null, retVal);
		return retVal;
	}
}
