package org.pathwayeditor.businessobjects.hibernate.pojos;

import java.io.Serializable;


import org.pathwayeditor.businessobjects.drawingprimitives.ILinkEndDecorator;
import org.pathwayeditor.businessobjects.drawingprimitives.ILinkTerminus;
import org.pathwayeditor.businessobjects.typedefn.ILinkEndDefinition;
import org.pathwayeditor.businessobjects.drawingprimitives.attributes.ArrowheadStyle;


/**
 * LinkEndDecorator generated by hbm2java
 */
public class HibLinkEndDecorator  implements ILinkEndDecorator ,Serializable {

	
     private Long id;
     private HibLinkTerminus hibLinkTerminus;
     private ArrowheadStyle decoratorType;
     private int width;
     private int height;
     private int gap ;

    public HibLinkEndDecorator() {
    }

    public HibLinkEndDecorator(HibLinkTerminus hibLinkTerminus, ArrowheadStyle decoratorType, int width, int height ) {
       this.hibLinkTerminus = hibLinkTerminus;
       this.decoratorType = decoratorType;
       this.width = width;
       this.height = height;
       this.gap = gap ;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
   
    public ILinkTerminus getLinkTerminus() {
        return this.hibLinkTerminus;
    }
    
    public HibLinkTerminus getHibLinkTerminus() {
        return this.hibLinkTerminus;
    } 
    
    public void setHibLinkTerminus(HibLinkTerminus hibLinkTerminus) {
        this.hibLinkTerminus = hibLinkTerminus;
    }
    public ArrowheadStyle getDecoratorType() {
        return this.decoratorType;
    }
    
    public void setDecoratorType(ArrowheadStyle decoratorType) {
        this.decoratorType = decoratorType;
    }
    public int getWidth() {
        return this.width;
    }
    
    public void setWidth(int width) {
        this.width = width;
    }
    public int getHeight() {
        return this.height;
    }
    
    public void setHeight(int height) {
        this.height = height;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HibLinkEndDecorator) ) return false;
		 HibLinkEndDecorator castOther = ( HibLinkEndDecorator ) other; 
         
		 return ( (this.getLinkTerminus()==castOther.getLinkTerminus()) || ( this.getLinkTerminus()!=null && castOther.getLinkTerminus()!=null && this.getLinkTerminus().equals(castOther.getLinkTerminus()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLinkTerminus() == null ? 0 : this.getLinkTerminus().hashCode() );
         
         return result;
   }   

	private static final long serialVersionUID = 6500668023572752002L;

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkEndDecoration#getLinkEnd()
	 */
	public ILinkTerminus getLinkEnd() {
		return this.hibLinkTerminus;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.ILinkEndDecoration#getLinkEndDefinition()
	 */
	public ILinkEndDefinition getLinkEndDefinition() {
		// TODO Auto-generated method stub
		return null;
	}
    	
  // end of extra code specified in the hbm.xml files

}


