package org.pathwayeditor.businessobjects.hibernate.pojos;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA



/**
 * MapDiagram generated by hbm2java
 */
public class HibMapDiagram  implements java.io.Serializable {


     private Long id;
     private HibFolder hibFolder;
     private String name;
     private String description;

    public HibMapDiagram() {
    }

    public HibMapDiagram(HibFolder hibFolder, String name, String description) {
       this.hibFolder = hibFolder;
       this.name = name;
       this.description = description;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public HibFolder getFolder() {
        return this.hibFolder;
    }
    
    public void setFolder(HibFolder hibFolder) {
        this.hibFolder = hibFolder;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HibMapDiagram) ) return false;
		 HibMapDiagram castOther = ( HibMapDiagram ) other; 
         
		 return ( (this.getFolder()==castOther.getFolder()) || ( this.getFolder()!=null && castOther.getFolder()!=null && this.getFolder().equals(castOther.getFolder()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         result = 37 * result + ( getFolder() == null ? 0 : this.getFolder().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         
         return result;
   }   

  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = -7566323206185334088L;
	
    public HibMapDiagram(HibFolder newParent, HibMapDiagram other){
    	this.hibFolder = newParent;
    	this.name = other.name;
    	this.description = other.description;
    }
   
	public void changeFolder(HibFolder newFolder){
	   HibFolder oldFolder = this.hibFolder;
	   this.hibFolder = newFolder;
	   if(oldFolder != null){
		   oldFolder.getMapDiagrams().remove(this);
	   }
	   if(this.hibFolder != null){
		   this.hibFolder.getMapDiagrams().add(this);
	   }
   }

	// end of extra code specified in the hbm.xml files

}


