package org.pathwayeditor.businessobjects.hibernate.pojos;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * NumberProperty generated by hbm2java
 */
public class HibNumberProperty extends HibProperty implements Serializable {


     private BigDecimal numberValue;
     private PropertyVisitor visitor = PropertyVisitor.getInstance();

    public HibNumberProperty() {
    }

    public HibNumberProperty(HibCanvas hibCanvas, int creationSerial, BigDecimal numberValue) {
        super(hibCanvas, creationSerial);        
       this.numberValue = numberValue;
    }
   
    public HibNumberProperty(HibCanvas newCanvas, HibNumberProperty other){
    	super(newCanvas, other);
    	numberValue = other.numberValue;
    }
    
    public BigDecimal getNumberValue() {
        return this.numberValue;
    }
    
    public void setNumberValue(BigDecimal numberValue) {
        this.numberValue = numberValue;
    }

    public HibNumberProperty copy(HibCanvas newCanvas){
    	return this.visitor.copyNumberProperty(newCanvas, this);
    }


  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = 1951406655193239331L;
    		
  // end of extra code specified in the hbm.xml files

}


