package org.pathwayeditor.businessobjects.hibernate.pojos;

import java.io.Serializable;



/**
 * ObjectType generated by hbm2java
 */
public class HibObjectType  implements Serializable {


     private Long id;
     private HibContext hibContext;
     private String name;
     private String description;

    public HibObjectType() {
    }

    public HibObjectType(HibContext hibContext, String name, String description) {
       this.hibContext = hibContext;
       this.name = name;
       this.description = description;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public HibContext getContext() {
        return this.hibContext;
    }
    
    public void setContext(HibContext hibContext) {
        this.hibContext = hibContext;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HibObjectType) ) return false;
		 HibObjectType castOther = ( HibObjectType ) other; 
         
		 return ( (this.getContext()==castOther.getContext()) || ( this.getContext()!=null && castOther.getContext()!=null && this.getContext().equals(castOther.getContext()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         result = 37 * result + ( getContext() == null ? 0 : this.getContext().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         
         return result;
   }   

  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = -1860135213188225684L;
    	
   public void changeContext(HibContext newContext){
	   HibContext oldContext = this.hibContext;
	   this.hibContext = newContext;
	   if(oldContext != null){
		   oldContext.getObjectTypes().remove(this);
	   }
	   if(this.hibContext != null){
		   this.hibContext.getObjectTypes().add(this);
	   }
   }
  // end of extra code specified in the hbm.xml files

}


