package org.pathwayeditor.businessobjects.hibernate.pojos;

import java.io.Serializable;

import org.pathwayeditor.businessobjects.pojos.IBusinessObjectData;
import org.pathwayeditor.businessobjects.pojos.RootFolder;
import org.pathwayeditor.businessobjects.repository.IRootFolder;

// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA


/**
 * RootFolder generated by hbm2java
 */
public class HibRootFolder extends HibFolder implements IBusinessObjectData<IRootFolder>, Serializable {
	private static final long serialVersionUID = 3780104587152506255L;
	private HibRepository hibRepository = null;
	private IRootFolder businessObject = null;

	public HibRootFolder() {
		super();
	}

	public HibRootFolder(HibRepository newDataStore, HibRootFolder other) {
		super(other);
		hibRepository = newDataStore;
	}

	public HibRootFolder(HibRepository hibRepository) {
		this.hibRepository = hibRepository;
	}

	public HibRepository getDataStore() {
		return this.hibRepository;
	}

	void setDataStore(HibRepository hibRepository) {
		this.hibRepository = hibRepository;
	}

	public void changeDataStore(HibRepository newDataStore) {
		HibRepository oldDataStore = this.hibRepository;
		this.hibRepository = newDataStore;
		if (oldDataStore != null) {
			oldDataStore.setRootFolder(null);
		}
		if (this.hibRepository != null) {
			this.hibRepository.setRootFolder(this);
		}
	}

	/**
	 * @return
	 */
	public IRootFolder getBusinessObject() {
		if(this.businessObject == null){
			this.businessObject = new RootFolder(this);
		}
		return this.businessObject;
	}

}
