package org.pathwayeditor.businessobjects.hibernate.pojos;

import java.io.Serializable;

import org.pathwayeditor.businessobjects.pojos.IBusinessObjectData;
import org.pathwayeditor.businessobjects.pojos.RootFolder;

// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA


/**
 * RootFolder generated by hbm2java
 */
public class HibRootFolder extends HibFolder implements IBusinessObjectData<RootFolder>, Serializable {
	private static final long serialVersionUID = 3780104587152506255L;
	private HibRepository hibRepository = null;
	private RootFolder businessObject = null;

	/**
	 * Default contructor typically used by hibernate.
	 */
	public HibRootFolder() {
		super();
	}

	/**
	 * Contructor used for new object created by a business object.
	 * @param businessObject
	 * @param repository
	 * @param other
	 */
	public HibRootFolder(RootFolder businessObject, HibRepository repository) {
		super();
		hibRepository = repository;
		this.businessObject = businessObject;
	}

	/**
	 * Copy constructor for hibernate object. Copies to a new repository that is provided.
	 * @param hibRepository
	 */
	public HibRootFolder(HibRepository newRepository, HibRootFolder other) {
		super(other);
		this.hibRepository = newRepository;
		this.businessObject = null;
	}

	public HibRepository getHibRepository() {
		return this.hibRepository;
	}

	void setHibRepository(HibRepository hibRepository) {
		this.hibRepository = hibRepository;
	}

	public void changeRepository(HibRepository newRepository) {
		HibRepository oldDataStore = this.hibRepository;
		this.hibRepository = newRepository;
		if (oldDataStore != null) {
			oldDataStore.setRootFolder(null);
		}
		if (this.hibRepository != null) {
			this.hibRepository.setRootFolder(this);
		}
	}

	/**
	 * @return
	 */
	public RootFolder getBusinessObject() {
		if(this.businessObject == null){
			this.businessObject = new RootFolder(this);
		}
		return this.businessObject;
	}

}
