package org.pathwayeditor.businessobjects.hibernate.pojos;

import java.io.Serializable;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA



/**
 * RichTextProperty generated by hbm2java
 */
public class HibRichTextProperty extends HibProperty implements Serializable {


     private String richTextValue;
     private PropertyVisitor visitor = PropertyVisitor.getInstance();

    public HibRichTextProperty() {
    }

    public HibRichTextProperty(HibCanvas hibCanvas, int creationSerial, String richTextValue) {
        super(hibCanvas, creationSerial);        
       this.richTextValue = richTextValue;
    }
    
    public HibRichTextProperty(HibCanvas newCanvas, HibRichTextProperty other){
    	super(newCanvas, other);
    	this.richTextValue = other.richTextValue;
    }
   
    public String getRichTextValue() {
        return this.richTextValue;
    }
    
    public void setRichTextValue(String richTextValue) {
        this.richTextValue = richTextValue;
    }

    public HibRichTextProperty copy(HibCanvas newCanvas){
    	return this.visitor.copyRichTextProperty(newCanvas, this);
    }

  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = -4043561259224207426L;
    		
  // end of extra code specified in the hbm.xml files

}


