package org.pathwayeditor.businessobjects.hibernate.pojos;

import org.pathwayeditor.businessobjects.drawingprimitives.properties.IHtmlAnnotationProperty;
import org.pathwayeditor.businessobjects.drawingprimitives.properties.IHtmlPropertyDefinition;
import org.pathwayeditor.businessobjects.drawingprimitives.properties.IPropertyDefinition;

/**
 * RichTextProperty generated by hbm2java
 */
public class HibRichTextProperty extends HibProperty implements IHtmlAnnotationProperty {
	private static final long serialVersionUID = -4043561259224207426L;

	private IHtmlPropertyDefinition propertyDefinition;
	private String richTextValue;

	/**
	 * Constructor should only be used by hiberate.
	 * @deprecated Application code should not use this constructor. Use one of the other constructors instead.
	 */
	HibRichTextProperty() {
	}

	public HibRichTextProperty(HibAnnotatedCanvasAttribute owner, IHtmlPropertyDefinition defn) {
		super(owner, defn);
		this.propertyDefinition = defn;
		this.richTextValue = defn.getDefaultValue();
	}

	public HibRichTextProperty(HibAnnotatedCanvasAttribute owner, HibRichTextProperty other) {
		super(owner, other);
		this.propertyDefinition = other.getDefinition();
		this.richTextValue = other.richTextValue;
	}

	public String getRichTextValue() {
		return this.richTextValue;
	}

	public void setValue(String richTextValue) {
		if (richTextValue == null)
			throw new IllegalArgumentException(
					"richText value should not be null.");
		this.richTextValue = richTextValue;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @seeorg.pathwayeditor.businessobjects.drawingprimitives.properties.
	 * IHtmlAnnotationProperty#getDefinition()
	 */
	public IHtmlPropertyDefinition getDefinition() {
		return this.propertyDefinition;
	}
	
	public void setPropertyDefinition(IPropertyDefinition propertyDefinition) {
		this.propertyDefinition = (IHtmlPropertyDefinition) propertyDefinition;
	}
	

	/*
	 * (non-Javadoc)
	 * 
	 * @seeorg.pathwayeditor.businessobjects.drawingprimitives.properties.
	 * IAnnotationProperty#getValue()
	 */
	public String getValue() {
		return this.richTextValue;
	}

}
