package org.pathwayeditor.businessobjects.hibernate.pojos;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import org.pathwayeditor.businessobjects.pojos.IBusinessObjectData;
import org.pathwayeditor.businessobjects.pojos.Repository;

/**
 * DataStore generated by hbm2java
 */
public class HibRepository implements IBusinessObjectData<Repository>, Serializable {
	private static final long serialVersionUID = -841109914395755034L;
	private Long id = null;
	private String name = null;
	private String description = null;
//	private HibRootFolder hibRootFolder = null;
	private Set<HibRootFolder> rootFolders = new HashSet<HibRootFolder>(0);
	private Repository businessObject = null;
	private int buildNum;

	public HibRepository() {
	}

	public HibRepository(String name, String description, int buildNum ) {
		this.name = name;
		this.description = description;
		this.buildNum = buildNum;
	}

	public HibRepository(HibRepository other) {
		this.name = other.name;
		this.description = other.description;
		this.buildNum = other.buildNum ;

		for(HibRootFolder rootFolder : other.rootFolders){
			this.rootFolders.add(new HibRootFolder(this, rootFolder));
		}
	}

	public Long getId() {
		return this.id;
	}

	void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<HibRootFolder> getRootFolders() {
		return this.rootFolders;
	}

	void setRootFolders(Set<HibRootFolder> hibRootFolders) {
		this.rootFolders = hibRootFolders;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("name").append("='").append(getName()).append("' ");
		buffer.append("description").append("='").append(getDescription())
				.append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HibRepository))
			return false;
		HibRepository castOther = (HibRepository) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null
				&& castOther.getName() != null && this.getName().equals(
				castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());

		return result;
	}

     void removeRootFolder(HibRootFolder rootFolder){
    	 if(rootFolder == null) throw new IllegalArgumentException("rootFolder cannot be null");
    	 if(rootFolder.getRepository() != this) throw new IllegalArgumentException("rootFolder must be a child of this folder");
    	 
    	 this.rootFolders.remove(rootFolder);
    	 rootFolder.setRepository(null);
     }
	
     void addRootFolder(HibRootFolder newRootFolder){
    	 if(newRootFolder == null) throw new IllegalArgumentException("newRootFolder cannot be null");
    	 
    	 HibRepository oldRepository = newRootFolder.getRepository();
    	 if(oldRepository != null){
    		 oldRepository.rootFolders.remove(newRootFolder);
    	 }
    	 this.rootFolders.add(newRootFolder);
    	 newRootFolder.setRepository(this);
     }

     public Repository getBusinessObject(){
		if(this.businessObject == null){
			this.businessObject = new Repository(this);
		}
		return this.businessObject;
	}
	
	public void setBuildNum(int buildNum){
		this.buildNum = buildNum;
	}
	
	public int getBuildNum(){
		return this.buildNum;
	}
}
