package org.pathwayeditor.businessobjects.hibernate.pojos;

import java.io.Serializable;

import org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotatedObject;
import org.pathwayeditor.businessobjects.drawingprimitives.properties.IPlainTextAnnotationProperty;
import org.pathwayeditor.businessobjects.typedefn.IPlainTextPropertyDefinition;



/**
 * TextProperty generated by hbm2java
 */
public class HibTextProperty extends HibProperty implements Serializable , IPlainTextAnnotationProperty{
	private static final long serialVersionUID = 2408749022194227955L;
	
	private String textValue;
	private final PropertyVisitor visitor = PropertyVisitor.getInstance();

    public HibTextProperty() {
    }

    public HibTextProperty(HibCanvas hibCanvas, int creationSerial, String textValue) {
        super(hibCanvas, creationSerial);        
       this.textValue = textValue;
    }
   
    
    public HibTextProperty(HibCanvas newCanvas, HibTextProperty other){
    	super(newCanvas, other);
    	this.textValue = other.textValue;
    }
    
    public String getTextValue() {
        return this.textValue;
    }
    
    public void setTextValue(String textValue) {
        this.textValue = textValue;
    }

    @Override
    public HibTextProperty copy(HibCanvas newCanvas){
    	return visitor.copyTextProperty(newCanvas, this);
    }

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IPlainTextAnnotationProperty#getDefinition()
	 */
	public IPlainTextPropertyDefinition getDefinition() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotationProperty#getOwningObject()
	 */
	public IAnnotatedObject getOwningObject() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotationProperty#getPropertySerial()
	 */
	public int getPropertySerial() {
		return super.getCreationSerial();
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotationProperty#getValue()
	 */
	public Object getValue() {
		return textValue;
	}
}


