package org.pathwayeditor.businessobjects.hibernate.pojos;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA


import java.util.HashMap;
import java.util.Map;

/**
 * LinkTerminus generated by hbm2java
 */
public class LinkTerminus  implements java.io.Serializable {


     private Long id;
     private Link link;
     private int linkEndType;
     private short offset;
     private LinkTerminusDecorator decorator;
     private LinkEndDecorator linkenddecorators;
     private Map<String,Property> properties = new HashMap<String,Property>(0);

    public LinkTerminus() {
    }

	
    public LinkTerminus(Link link, int linkEndType, short offset) {
        this.link = link;
        this.linkEndType = linkEndType;
        this.offset = offset;
    }
    public LinkTerminus(Link link, int linkEndType, short offset, LinkTerminusDecorator decorator, LinkEndDecorator linkenddecorators, Map<String,Property> properties) {
       this.link = link;
       this.linkEndType = linkEndType;
       this.offset = offset;
       this.decorator = decorator;
       this.linkenddecorators = linkenddecorators;
       this.properties = properties;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Link getLink() {
        return this.link;
    }
    
    public void setLink(Link link) {
        this.link = link;
    }
    public int getLinkEndType() {
        return this.linkEndType;
    }
    
    public void setLinkEndType(int linkEndType) {
        this.linkEndType = linkEndType;
    }
    public short getOffset() {
        return this.offset;
    }
    
    public void setOffset(short offset) {
        this.offset = offset;
    }
    public LinkTerminusDecorator getDecorator() {
        return this.decorator;
    }
    
    public void setDecorator(LinkTerminusDecorator decorator) {
        this.decorator = decorator;
    }
    public LinkEndDecorator getLinkenddecorators() {
        return this.linkenddecorators;
    }
    
    public void setLinkenddecorators(LinkEndDecorator linkenddecorators) {
        this.linkenddecorators = linkenddecorators;
    }
    public Map<String,Property> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Map<String,Property> properties) {
        this.properties = properties;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LinkTerminus) ) return false;
		 LinkTerminus castOther = ( LinkTerminus ) other; 
         
		 return ( (this.getLink()==castOther.getLink()) || ( this.getLink()!=null && castOther.getLink()!=null && this.getLink().equals(castOther.getLink()) ) )
 && (this.getLinkEndType()==castOther.getLinkEndType());
   }
   
   public int hashCode() {
         int result = 17;
         
         
         result = 37 * result + ( getLink() == null ? 0 : this.getLink().hashCode() );
         result = 37 * result + this.getLinkEndType();
         
         
         
         
         return result;
   }   

  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = -4462637156010353035L;
    	
  // end of extra code specified in the hbm.xml files

}


