package org.pathwayeditor.businessobjects.hibernate.pojos;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.List;

/**
 * ListProperty generated by hbm2java
 */
public class ListProperty extends org.pathwayeditor.businessobjects.hibernate.pojos.Property implements java.io.Serializable {


     private List<String> values = new ArrayList<String>(0);
     private final PropertyVisitor visitor = PropertyVisitor.getInstance();

    public ListProperty() {
    }

	
    public ListProperty(Canvas canvas, int creationSerial) {
        super(canvas, creationSerial);        
    }
    public ListProperty(Canvas canvas, int creationSerial, List<String> values) {
        super(canvas, creationSerial);        
       this.values = values;
    }
   
    public ListProperty(Canvas newCanvas, ListProperty listProperty){
    	super(newCanvas, listProperty);
    }
    
    public ListProperty copy(Canvas newCanvas){
    	return this.visitor.copyListProperty(newCanvas, this);
    }
    
    public List<String> getValues() {
        return this.values;
    }
    
    public void setValues(List<String> values) {
        this.values = values;
    }

  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = 3772272140640145846L;
    		
  // end of extra code specified in the hbm.xml files

}


