package org.pathwayeditor.businessobjects.hibernate.pojos;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA



/**
 * MapDiagram generated by hbm2java
 */
public class MapDiagram  implements java.io.Serializable {


     private Long id;
     private Folder folder;
     private String name;
     private String description;

    public MapDiagram() {
    }

    public MapDiagram(Folder folder, String name, String description) {
       this.folder = folder;
       this.name = name;
       this.description = description;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Folder getFolder() {
        return this.folder;
    }
    
    public void setFolder(Folder folder) {
        this.folder = folder;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MapDiagram) ) return false;
		 MapDiagram castOther = ( MapDiagram ) other; 
         
		 return ( (this.getFolder()==castOther.getFolder()) || ( this.getFolder()!=null && castOther.getFolder()!=null && this.getFolder().equals(castOther.getFolder()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         result = 37 * result + ( getFolder() == null ? 0 : this.getFolder().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         
         return result;
   }   

  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = -7566323206185334088L;
	
    public MapDiagram(Folder newParent, MapDiagram other){
    	this.folder = newParent;
    	this.name = other.name;
    	this.description = other.description;
    }
   
	public void changeFolder(Folder newFolder){
	   Folder oldFolder = this.folder;
	   this.folder = newFolder;
	   if(oldFolder != null){
		   oldFolder.getMapDiagrams().remove(this);
	   }
	   if(this.folder != null){
		   this.folder.getMapDiagrams().add(this);
	   }
   }

	// end of extra code specified in the hbm.xml files

}


