package org.pathwayeditor.businessobjects.hibernate.pojos;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA


import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * NonRootShape generated by hbm2java
 */
public class NonRootShape extends org.pathwayeditor.businessobjects.hibernate.pojos.Shape implements java.io.Serializable {


     private Shape parentShape;
     private int childIndex;

    public NonRootShape() {
    }

	
    public NonRootShape(int XPosition, int YPosition, int width, int height, ObjectType objectType, String name, String description, String detailedDescription, String url, int fillRed, int fillGreen, int fillBlue, int lineRed, int lineGreen, int lineBlue, int lineStyle, int lineWidth, int padding, short shapeType, Shape parentShape, int childIndex) {
        super(XPosition, YPosition, width, height, objectType, name, description, detailedDescription, url, fillRed, fillGreen, fillBlue, lineRed, lineGreen, lineBlue, lineStyle, lineWidth, padding, shapeType);        
        this.parentShape = parentShape;
        this.childIndex = childIndex;
    }
    public NonRootShape(int XPosition, int YPosition, int width, int height, ObjectType objectType, String name, String description, String detailedDescription, String url, int fillRed, int fillGreen, int fillBlue, int lineRed, int lineGreen, int lineBlue, int lineStyle, int lineWidth, int padding, short shapeType, List<NonRootShape> childShapes, Set<Link> linksFromSource, Set<Link> linksFromTarget, Map<String,Property> properties, Shape parentShape, int childIndex) {
        super(XPosition, YPosition, width, height, objectType, name, description, detailedDescription, url, fillRed, fillGreen, fillBlue, lineRed, lineGreen, lineBlue, lineStyle, lineWidth, padding, shapeType, childShapes, linksFromSource, linksFromTarget, properties);        
       this.parentShape = parentShape;
       this.childIndex = childIndex;
    }
   
    public Shape getParentShape() {
        return this.parentShape;
    }
    
     void setParentShape(Shape parentShape) {
        this.parentShape = parentShape;
    }
    public int getChildIndex() {
        return this.childIndex;
    }
    
    public void setChildIndex(int childIndex) {
        this.childIndex = childIndex;
    }



  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = 1669623191042510228L;

	public NonRootShape(Shape newParent, NonRootShape other){
		super(other);
		this.parentShape = newParent;
		this.childIndex = other.childIndex;
	}

    public void changeParentShape(Shape newParentShape){
	   Shape oldParentShape = this.parentShape;
	   this.parentShape = newParentShape;
	   if(oldParentShape != null){
		   oldParentShape.getChildShapes().remove(this);
	   }
	   if(this.parentShape != null){
		   this.parentShape.getChildShapes().add(this);
	   }
   }


	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.hibernate.pojos.Shape#getCanvas()
	 */
	@Override
	public Canvas getCanvas() {
		return this.parentShape.getCanvas();
	}
        	
  // end of extra code specified in the hbm.xml files

}


