package org.pathwayeditor.businessobjects.hibernate.pojos;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA



/**
 * RootShape generated by hbm2java
 */
public class RootShape extends org.pathwayeditor.businessobjects.hibernate.pojos.Shape implements java.io.Serializable {
	private static final long serialVersionUID = -1230930447658096763L;

     private Canvas canvas;
     private int shapeIndex;

    public RootShape() {
    }

	
    public Canvas getCanvas() {
        return this.canvas;
    }
    
     void setCanvas(Canvas canvas) {
        this.canvas = canvas;
    }
    public int getShapeIndex() {
        return this.shapeIndex;
    }
    
    public void setShapeIndex(int shapeIndex) {
        this.shapeIndex = shapeIndex;
    }



  // The following is extra code specified in the hbm.xml files

    public RootShape(Canvas newCanvas, RootShape other){
    	super(other);
    	this.canvas = newCanvas;
    	this.shapeIndex = other.shapeIndex;
    }
        	
   public void changeCanvas(Canvas newCanvas){
	   Canvas oldCanvas = this.canvas;
	   this.canvas = newCanvas;
	   if(oldCanvas != null){
		   oldCanvas.getShapes().remove(this);
	   }
	   if(this.canvas != null){
		   this.canvas.getShapes().add(this);
	   }
   }

    // end of extra code specified in the hbm.xml files

}


