package org.pathwayeditor.businessobjects.hibernate.pojos;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA


import java.util.Set;

/**
 * RootFolder generated by hbm2java
 */
public class RootFolder extends org.pathwayeditor.businessobjects.hibernate.pojos.Folder implements java.io.Serializable {


     private DataStore dataStore;

    public RootFolder() {
    }

	
    public RootFolder(DataStore dataStore) {
        this.dataStore = dataStore;
    }
    public RootFolder(Set<MapDiagram> mapDiagrams, Set<NonRootFolder> subFolders, DataStore dataStore) {
        super(mapDiagrams, subFolders);        
       this.dataStore = dataStore;
    }
   
    public DataStore getDataStore() {
        return this.dataStore;
    }
    
     void setDataStore(DataStore dataStore) {
        this.dataStore = dataStore;
    }



  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = 3780104587152506255L;

    public RootFolder(DataStore newDataStore, RootFolder other){
    	super(other);
    	dataStore = newDataStore;
    }
	
    public void changeDataStore(DataStore newDataStore){
	   DataStore oldDataStore = this.dataStore;
	   this.dataStore = newDataStore;
	   if(oldDataStore != null){
		   oldDataStore.setRootFolder(null);
	   }
	   if(this.dataStore != null){
		   this.dataStore.setRootFolder(this);
	   }
   }
    		
  // end of extra code specified in the hbm.xml files

}


