package org.pathwayeditor.businessobjects.hibernate.pojos;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Shape generated by hbm2java
 */
public abstract class Shape  implements java.io.Serializable {


     private Long id;
     private int XPosition;
     private int YPosition;
     private int width;
     private int height;
     private ObjectType objectType;
     private String name;
     private String description;
     private String detailedDescription;
     private String url;
     private int fillRed;
     private int fillGreen;
     private int fillBlue;
     private int lineRed;
     private int lineGreen;
     private int lineBlue;
     private int lineStyle;
     private int lineWidth;
     private int padding;
     private short shapeType;
     private List<NonRootShape> childShapes = new ArrayList<NonRootShape>(0);
     private Set<Link> linksFromSource = new HashSet<Link>(0);
     private Set<Link> linksFromTarget = new HashSet<Link>(0);
     private Map<String,Property> properties = new HashMap<String,Property>(0);

    public Shape() {
    }

	
    public Shape(int XPosition, int YPosition, int width, int height, ObjectType objectType, String name, String description, String detailedDescription, String url, int fillRed, int fillGreen, int fillBlue, int lineRed, int lineGreen, int lineBlue, int lineStyle, int lineWidth, int padding, short shapeType) {
        this.XPosition = XPosition;
        this.YPosition = YPosition;
        this.width = width;
        this.height = height;
        this.objectType = objectType;
        this.name = name;
        this.description = description;
        this.detailedDescription = detailedDescription;
        this.url = url;
        this.fillRed = fillRed;
        this.fillGreen = fillGreen;
        this.fillBlue = fillBlue;
        this.lineRed = lineRed;
        this.lineGreen = lineGreen;
        this.lineBlue = lineBlue;
        this.lineStyle = lineStyle;
        this.lineWidth = lineWidth;
        this.padding = padding;
        this.shapeType = shapeType;
    }
    public Shape(int XPosition, int YPosition, int width, int height, ObjectType objectType, String name, String description, String detailedDescription, String url, int fillRed, int fillGreen, int fillBlue, int lineRed, int lineGreen, int lineBlue, int lineStyle, int lineWidth, int padding, short shapeType, List<NonRootShape> childShapes, Set<Link> linksFromSource, Set<Link> linksFromTarget, Map<String,Property> properties) {
       this.XPosition = XPosition;
       this.YPosition = YPosition;
       this.width = width;
       this.height = height;
       this.objectType = objectType;
       this.name = name;
       this.description = description;
       this.detailedDescription = detailedDescription;
       this.url = url;
       this.fillRed = fillRed;
       this.fillGreen = fillGreen;
       this.fillBlue = fillBlue;
       this.lineRed = lineRed;
       this.lineGreen = lineGreen;
       this.lineBlue = lineBlue;
       this.lineStyle = lineStyle;
       this.lineWidth = lineWidth;
       this.padding = padding;
       this.shapeType = shapeType;
       this.childShapes = childShapes;
       this.linksFromSource = linksFromSource;
       this.linksFromTarget = linksFromTarget;
       this.properties = properties;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public int getXPosition() {
        return this.XPosition;
    }
    
    public void setXPosition(int XPosition) {
        this.XPosition = XPosition;
    }
    public int getYPosition() {
        return this.YPosition;
    }
    
    public void setYPosition(int YPosition) {
        this.YPosition = YPosition;
    }
    public int getWidth() {
        return this.width;
    }
    
    public void setWidth(int width) {
        this.width = width;
    }
    public int getHeight() {
        return this.height;
    }
    
    public void setHeight(int height) {
        this.height = height;
    }
    public ObjectType getObjectType() {
        return this.objectType;
    }
    
     void setObjectType(ObjectType objectType) {
        this.objectType = objectType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDetailedDescription() {
        return this.detailedDescription;
    }
    
    public void setDetailedDescription(String detailedDescription) {
        this.detailedDescription = detailedDescription;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public int getFillRed() {
        return this.fillRed;
    }
    
    public void setFillRed(int fillRed) {
        this.fillRed = fillRed;
    }
    public int getFillGreen() {
        return this.fillGreen;
    }
    
    public void setFillGreen(int fillGreen) {
        this.fillGreen = fillGreen;
    }
    public int getFillBlue() {
        return this.fillBlue;
    }
    
    public void setFillBlue(int fillBlue) {
        this.fillBlue = fillBlue;
    }
    public int getLineRed() {
        return this.lineRed;
    }
    
    public void setLineRed(int lineRed) {
        this.lineRed = lineRed;
    }
    public int getLineGreen() {
        return this.lineGreen;
    }
    
    public void setLineGreen(int lineGreen) {
        this.lineGreen = lineGreen;
    }
    public int getLineBlue() {
        return this.lineBlue;
    }
    
    public void setLineBlue(int lineBlue) {
        this.lineBlue = lineBlue;
    }
    public int getLineStyle() {
        return this.lineStyle;
    }
    
    public void setLineStyle(int lineStyle) {
        this.lineStyle = lineStyle;
    }
    public int getLineWidth() {
        return this.lineWidth;
    }
    
    public void setLineWidth(int lineWidth) {
        this.lineWidth = lineWidth;
    }
    public int getPadding() {
        return this.padding;
    }
    
    public void setPadding(int padding) {
        this.padding = padding;
    }
    public short getShapeType() {
        return this.shapeType;
    }
    
    public void setShapeType(short shapeType) {
        this.shapeType = shapeType;
    }
    public List<NonRootShape> getChildShapes() {
        return this.childShapes;
    }
    
    public void setChildShapes(List<NonRootShape> childShapes) {
        this.childShapes = childShapes;
    }
    public Set<Link> getLinksFromSource() {
        return this.linksFromSource;
    }
    
    public void setLinksFromSource(Set<Link> linksFromSource) {
        this.linksFromSource = linksFromSource;
    }
    public Set<Link> getLinksFromTarget() {
        return this.linksFromTarget;
    }
    
    public void setLinksFromTarget(Set<Link> linksFromTarget) {
        this.linksFromTarget = linksFromTarget;
    }
    public Map<String,Property> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Map<String,Property> properties) {
        this.properties = properties;
    }



  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = -8557015458835029042L;

    public Shape(Shape other){
    	this.XPosition = other.XPosition;
    	this.YPosition = other.YPosition;
    	this.width = other.width;
    	this.height = other.height;
    	this.objectType = other.objectType;
    	this.name = other.name;
    	this.description = other.description;
    	this.detailedDescription = other.detailedDescription;
    	this.url = other.url;
    	this.fillRed = other.fillRed;
    	this.fillGreen = other.fillGreen;
    	this.fillBlue = other.fillBlue;
    	this.lineRed = other.lineRed;
    	this.lineGreen = other.lineGreen;
    	this.lineBlue = other.lineBlue;
    	this.lineStyle = other.lineStyle;
    	this.lineWidth = other.lineWidth;
    	this.padding = other.padding;
    	for(NonRootShape childShape : other.childShapes){
    		this.childShapes.add(new NonRootShape(this, childShape));
    	}
    	for(String propertyName : other.properties.keySet()){
    		Property otherProp = other.properties.get(propertyName);
    		this.properties.put(propertyName, otherProp.copy(getCanvas()));
    	}
    }

    public abstract Canvas getCanvas();
    
     void addChildShape(NonRootShape newChildShape){
    	 if(newChildShape == null) throw new IllegalArgumentException("newChildShape cannot be null");
    	 
    	 Shape oldParentShape = newChildShape.getParentShape();
    	 if(oldParentShape != null){
    		 oldParentShape.childShapes.remove(newChildShape);
    	 }
    	 this.childShapes.add(newChildShape);
    	 newChildShape.setParentShape(this);
     }

     void removeChildShape(NonRootShape childShape){
    	 if(childShape == null) throw new IllegalArgumentException("childShape cannot be null");
    	 if(childShape.getParentShape() != this) throw new IllegalArgumentException("childShape must be a child of this folder");
    	 
    	 this.childShapes.remove(childShape);
    	 childShape.setParentShape(null);
     }
     // end of extra code specified in the hbm.xml files

}


