package org.pathwayeditor.businessobjects.hibernate.pojos;
// Generated 07-May-2008 22:43:44 by Hibernate Tools 3.2.1.GA



/**
 * TextProperty generated by hbm2java
 */
public class TextProperty extends org.pathwayeditor.businessobjects.hibernate.pojos.Property implements java.io.Serializable {
	private static final long serialVersionUID = 2408749022194227955L;
	
	private String textValue;
	private final PropertyVisitor visitor = PropertyVisitor.getInstance();

    public TextProperty() {
    }

    public TextProperty(Canvas canvas, int creationSerial, String textValue) {
        super(canvas, creationSerial);        
       this.textValue = textValue;
    }
   
    
    public TextProperty(Canvas newCanvas, TextProperty other){
    	super(newCanvas, other);
    	this.textValue = other.textValue;
    }
    
    public String getTextValue() {
        return this.textValue;
    }
    
    public void setTextValue(String textValue) {
        this.textValue = textValue;
    }

    @Override
    public TextProperty copy(Canvas newCanvas){
    	return visitor.copyTextProperty(newCanvas, this);
    }
}


