/*
Copyright 2009, Court of the University of Edinburgh

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. 
*/
/**
 * 
 */
package org.pathwayeditor.businessobjects.database.util;

import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.pathwayeditor.businessobjects.management.IConnectionInfo;

/**
 * @author nhanlon 
 * Class to handle passing data to and from hibconfig
 *
 */
public class HibernateDataSource {
	public static final String HIB_PROP_DRIVER_CLASS = "hibernate.connection.driver_class";
	public static final String HIB_PROP_URL = "hibernate.connection.url";
	public static final String HIB_PROP_USERNAME = "hibernate.connection.username";
	public static final String HIB_PROP_PASSWORD = "hibernate.connection.password";
	private Configuration hibConfig;
	private String driverClass;
	private String connectionUrl;
	private String userName;
	private String password;

	/**
	 * @param xmlConfigFile
	 */
	public HibernateDataSource(String xmlConfigFile) {
		Configuration hibConf = new Configuration();
		this.hibConfig = hibConf.configure(xmlConfigFile);
		this.driverClass = hibConfig.getProperty(HIB_PROP_DRIVER_CLASS);
		this.connectionUrl = hibConfig.getProperty(HIB_PROP_URL);
		this.userName = hibConfig.getProperty(HIB_PROP_USERNAME);
		this.password = hibConfig.getProperty(HIB_PROP_PASSWORD);
	}

	public HibernateDataSource(String xmlConfigFile, IConnectionInfo connInfo) {
		this(xmlConfigFile);
		this.setConnectionInfo(connInfo);
	}

		public String getDriverClass() {
		return this.driverClass;
	}

	public String getConnectionUrl() {
		return this.connectionUrl;
	}

	public String getUserName() {
		return this.userName;
	}

	public String getPassword() {
		return this.password;
	}

	/**
	 * @return hibernate sessionfactory generated by this instance (note generation is expensive and so 
	 * sessionfactory should be used as a singleton)
	 */
	public SessionFactory getSessionFactory() {
		return hibConfig.buildSessionFactory();
	}

	/**
	 * @return hibconfig  - generated by this instance
	 */
	public Configuration getHibConfig() {
		return hibConfig;
	}

	/**
	 * @param conn information for a jdbc connection
	 */
	public void setConnectionInfo(IConnectionInfo conn) {
		hibConfig.setProperty(HibernateDataSource.HIB_PROP_DRIVER_CLASS,conn.getDriverName());
		hibConfig.setProperty(HibernateDataSource.HIB_PROP_URL,conn.getUrl());
		hibConfig.setProperty(HibernateDataSource.HIB_PROP_USERNAME,conn.getUserName());
		hibConfig.setProperty(HibernateDataSource.HIB_PROP_PASSWORD, conn.getPassword());
	}

}
