/**
 * 
 */
package org.pathwayeditor.businessobjects.database.util;

import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

/**
 * @author nhanlon 
 * Class to handle passing data to and from hibconfig
 *
 */
public class HibernateDataSource {
	public static final String HIB_PROP_DRIVER_CLASS = "hibernate.connection.driver_class";
	public static final String HIB_PROP_URL = "hibernate.connection.url";
	public static final String HIB_PROP_USERNAME = "hibernate.connection.username";
	public static final String HIB_PROP_PASSWORD = "hibernate.connection.password";
	public static final String HIB_DIALECT="hibernate.dialect";
	public static final String HIB_SESS_CONTEXT="hibernate.current_session_context_class";
	private Configuration hibConfig;
	/**
	 * @param conn a connectioninfo object with setup paramaters for Hibernate
	 */
	public HibernateDataSource(IConnectionInfo conn) {
		hibConfig = new Configuration().configure("hibernate.cfg.xml");//sets up class mappings and default connection settings
		hibConfig.setProperty(HIB_PROP_DRIVER_CLASS,conn.getDriverName());
		hibConfig.setProperty(HIB_PROP_URL,conn.getUrl());
		hibConfig.setProperty(HIB_PROP_USERNAME,conn.getUserName());
		hibConfig.setProperty(HIB_PROP_PASSWORD, conn.getPassword());
		hibConfig.setProperty(HIB_DIALECT, conn.getDialect());
		hibConfig.setProperty(HIB_SESS_CONTEXT, conn.getSessionContext());
	}

	public String getDriverClass() {
		return hibConfig.getProperty(HIB_PROP_DRIVER_CLASS);
	}

	public String getConnectionUrl() {
		return hibConfig.getProperty(HIB_PROP_URL);
	}

	public String getUserName() {
		return hibConfig.getProperty(HIB_PROP_USERNAME);
	}

	public String getPassword() {
		return  hibConfig.getProperty(HIB_PROP_PASSWORD);
	}

	/**
	 * @return hibernate sessionfactory generated by this instance (note generation is expensive and so 
	 * sessionfactory should be used as a singleton)
	 */
	public SessionFactory getSessionFactory() {
		return hibConfig.buildSessionFactory();
	}

	/**
	 * @return hibconfig  - generated by this instance
	 */
	public Configuration getHibConfig() {
		return hibConfig;
	}

}
