/**
 * 
 */
package org.pathwayeditor.businessobjects.drawingprimitives.listeners;

/**
 * @author smoodie
 *
 */
public enum PropertyChange {
	GRID_SIZE, GRID_SHOWN, SNAP_TO_GRID_ENABLED, BACKGROUND_COLOUR, CANVAS_SIZE,
	SIZE, LOCATION, FILL_COLOUR, LINE_COLOUR, LINE_STYLE, LINE_WIDTH,
	NAME, DESCRIPTION, DETAILED_DESCRIPTION, URL, PRIMITIVE_SHAPE_TYPE,
	PADDING, ROUTER_TYPE, BEND_POINT_ADDED, BEND_POINT_REMOVED, BEND_POINT_REINDEXED,
	END_DECORATOR_TYPE, END_DECORATOR_SIZE, TERMINUS_GAP, TERMINUS_DECORATOR_TYPE,
	TERMINUS_DEC_COLOUR, TERMINUS_SIZE , NAME_VISIBLE , ALIGNMENT
}
