package org.pathwayeditor.businessobjects.hibernate.pojos;

import java.io.Serializable;

import org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotatedObject;
import org.pathwayeditor.businessobjects.drawingprimitives.properties.IHtmlAnnotationProperty;
import org.pathwayeditor.businessobjects.drawingprimitives.properties.IHtmlPropertyDefinition;
import org.pathwayeditor.businessobjects.drawingprimitives.properties.IVisualisableAnnotationProperty;



/**
 * RichTextProperty generated by hbm2java
 */
public class HibRichTextProperty extends HibProperty implements Serializable , IHtmlAnnotationProperty {


     private String richTextValue;
     private PropertyVisitor visitor = PropertyVisitor.getInstance();

    public HibRichTextProperty() {
    }

    public HibRichTextProperty(HibCanvas hibCanvas, int creationSerial, String richTextValue) {
        super(hibCanvas, creationSerial);        
       this.richTextValue = richTextValue;
    }
    
    public HibRichTextProperty(HibCanvas newCanvas, HibRichTextProperty other){
    	super(newCanvas, other);
    	this.richTextValue = other.richTextValue;
    }
   
    public String getRichTextValue() {
        return this.richTextValue;
    }
    
    public void setRichTextValue(String richTextValue) {
    	if ( richTextValue == null)
    		throw new IllegalArgumentException ( "richText value should not be null." ) ;
        this.richTextValue = richTextValue;
    }

    public HibRichTextProperty copy(HibCanvas newCanvas){
    	return this.visitor.copyRichTextProperty(newCanvas, this);
    }

  // The following is extra code specified in the hbm.xml files

	private static final long serialVersionUID = -4043561259224207426L;

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IHtmlAnnotationProperty#getDefinition()
	 */
	public IHtmlPropertyDefinition getDefinition() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IHtmlAnnotationProperty#setValue(java.lang.String)
	 */
	public void setValue(String newText) {
		this.richTextValue = newText ;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotationProperty#getOwningObject()
	 */
	public IAnnotatedObject getOwningObject() {
		// TODO Auto-generated method stub
		throw new UnsupportedOperationException () ;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotationProperty#getPropertySerial()
	 */
	public int getPropertySerial() {
		return super.getCreationSerial();
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IAnnotationProperty#getValue()
	 */
	public Object getValue() {
		return this.richTextValue;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IVisualisableAnnotationProperty#getProperty()
	 */
	public IVisualisableAnnotationProperty getProperty() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IVisualisableAnnotationProperty#isDisplayed()
	 */
	public boolean isDisplayed() {
		// TODO Auto-generated method stub
		return false;
	}

	/* (non-Javadoc)
	 * @see org.pathwayeditor.businessobjects.drawingprimitives.properties.IVisualisableAnnotationProperty#setDisplayed(boolean)
	 */
	public void setDisplayed(boolean displayed) {
		// TODO Auto-generated method stub
		
	}
    		
  // end of extra code specified in the hbm.xml files

}


