package org.pathwayeditor.businessobjects.hibernate.pojos;

import org.pathwayeditor.businessobjects.drawingprimitives.properties.IPlainTextAnnotationProperty;
import org.pathwayeditor.businessobjects.drawingprimitives.properties.IPlainTextPropertyDefinition;

/**
 * TextProperty generated by hbm2java
 */
public class HibTextProperty extends HibProperty implements IPlainTextAnnotationProperty {
	private static final long serialVersionUID = 2408749022194227955L;

	private String textValue;
	private IPlainTextPropertyDefinition propDefn;

	/**
	 * Constructor should only be used by hiberate.
	 * @deprecated Application code should not use this constructor. Use one of the other constructors instead.
	 */
	HibTextProperty() {
	}

	public HibTextProperty(HibCanvas hibCanvas, int creationSerial, IPlainTextPropertyDefinition defn) {
		super(hibCanvas, creationSerial);
		this.propDefn = defn;
		this.textValue = defn.getDefaultValue();
	}

	public HibTextProperty(HibCanvas newCanvas, int newCreationSerial, HibTextProperty other) {
		super(newCanvas, newCreationSerial, other);
		this.propDefn = other.propDefn;
		this.textValue = other.textValue;
	}

	public void setValue(String textValue) {
		if (textValue == null)
			throw new IllegalArgumentException("Text value cannot be null.");

		this.textValue = textValue;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @seeorg.pathwayeditor.businessobjects.drawingprimitives.properties.
	 * IPlainTextAnnotationProperty#getDefinition()
	 */
	public IPlainTextPropertyDefinition getDefinition() {
		return this.propDefn;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @seeorg.pathwayeditor.businessobjects.drawingprimitives.properties.
	 * IAnnotationProperty#getValue()
	 */
	public String getValue() {
		return textValue;
	}
}
